export interface ILanguage {
    code: string;
    name: string;
}

export const languages: ILanguage[] = [
    { code: "ad", name: "Andorra" },
    { code: "ae", name: "الإمارات العربية المتحدة" },
    { code: "af", name: "افغانستان" },
    { code: "ag", name: "Antigua and Barbuda" },
    { code: "ai", name: "Anguilla" },
    { code: "al", name: "Shqipëria" },
    { code: "am", name: "Հայաստան" },
    { code: "ao", name: "Angola" },
    { code: "aq", name: "Antarctica" },
    { code: "ar", name: "Argentina" },
    { code: "as", name: "American Samoa" },
    { code: "at", name: "Österreich" },
    { code: "au", name: "Australia" },
    { code: "aw", name: "Aruba" },
    { code: "ax", name: "Åland" },
    { code: "az", name: "Azərbaycan" },
    { code: "ba", name: "Bosna i Hercegovina" },
    { code: "bb", name: "Barbados" },
    { code: "bd", name: "বাংলাদেশ" },
    { code: "be", name: "België" },
    { code: "bf", name: "Burkina Faso" },
    { code: "bg", name: "България" },
    { code: "bh", name: "البحرين" },
    { code: "bi", name: "Burundi" },
    { code: "bj", name: "Bénin" },
    { code: "bl", name: "Saint-Barthélemy" },
    { code: "bm", name: "Bermuda" },
    { code: "bn", name: "Brunei Darussalam" },
    { code: "bo", name: "Bolivia" },
    { code: "bq", name: "Bonaire" },
    { code: "br", name: "Brasil" },
    { code: "bs", name: "Bahamas" },
    { code: "bt", name: "འབྲུག" },
    { code: "bv", name: "Bouvetøya" },
    { code: "bw", name: "Botswana" },
    { code: "by", name: "Беларусь" },
    { code: "bz", name: "Belize" },
    { code: "ca", name: "Canada" },
    { code: "cc", name: "Cocos (Keeling) Islands" },
    { code: "cd", name: "République démocratique du Congo" },
    { code: "cf", name: "République centrafricaine" },
    { code: "cg", name: "République du Congo" },
    { code: "ch", name: "Schweiz" },
    { code: "ci", name: "Côte d'Ivoire" },
    { code: "ck", name: "Cook Islands" },
    { code: "cl", name: "Chile" },
    { code: "cm", name: "Cameroun" },
    { code: "cn", name: "中国" },
    { code: "co", name: "Colombia" },
    { code: "cr", name: "Costa Rica" },
    { code: "cu", name: "Cuba" },
    { code: "cv", name: "Cabo Verde" },
    { code: "cw", name: "Curaçao" },
    { code: "cx", name: "Christmas Island" },
    { code: "cy", name: "Κύπρος" },
    { code: "cz", name: "Česká republika" },
    { code: "de", name: "Deutschland" },
    { code: "dj", name: "Djibouti" },
    { code: "dk", name: "Danmark" },
    { code: "dm", name: "Dominica" },
    { code: "do", name: "República Dominicana" },
    { code: "dz", name: "الجزائر" },
    { code: "ec", name: "Ecuador" },
    { code: "ee", name: "Eesti" },
    { code: "eg", name: "مصر" },
    { code: "eh", name: "الصحراء الغربية" },
    { code: "er", name: "ኤርትራ" },
    { code: "es", name: "España" },
    { code: "et", name: "ኢትዮጵያ" },
    { code: "fi", name: "Suomi" },
    { code: "fj", name: "Fiji" },
    { code: "fk", name: "Falkland Islands" },
    { code: "fm", name: "Micronesia" },
    { code: "fo", name: "Føroyar" },
    { code: "fr", name: "France" },
    { code: "ga", name: "Gabon" },
    { code: "gb", name: "United Kingdom" },
    { code: "gd", name: "Grenada" },
    { code: "ge", name: "საქართველო" },
    { code: "gf", name: "Guyane française" },
    { code: "gg", name: "Guernsey" },
    { code: "gh", name: "Ghana" },
    { code: "gi", name: "Gibraltar" },
    { code: "gl", name: "Kalaallit Nunaat" },
    { code: "gm", name: "Gambia" },
    { code: "gn", name: "Guinée" },
    { code: "gp", name: "Guadeloupe" },
    { code: "gq", name: "Guinea Ecuatorial" },
    { code: "gr", name: "Ελλάδα" },
    { code: "gs", name: "South Georgia" },
    { code: "gt", name: "Guatemala" },
    { code: "gu", name: "Guam" },
    { code: "gw", name: "Guiné-Bissau" },
    { code: "gy", name: "Guyana" },
    { code: "hk", name: "香港" },
    { code: "hm", name: "Heard Island and McDonald Islands" },
    { code: "hn", name: "Honduras" },
    { code: "hr", name: "Hrvatska" },
    { code: "ht", name: "Haïti" },
    { code: "hu", name: "Magyarország" },
    { code: "id", name: "Indonesia" },
    { code: "ie", name: "Éire" },
    { code: "il", name: "יִשְׂרָאֵל" },
    { code: "im", name: "Isle of Man" },
    { code: "in", name: "भारत" },
    { code: "io", name: "British Indian Ocean Territory" },
    { code: "iq", name: "العراق" },
    { code: "ir", name: "ایران" },
    { code: "is", name: "Ísland" },
    { code: "it", name: "Italia" },
    { code: "je", name: "Jersey" },
    { code: "jm", name: "Jamaica" },
    { code: "jo", name: "الأردن" },
    { code: "jp", name: "日本" },
    { code: "ke", name: "Kenya" },
    { code: "kg", name: "Кыргызстан" },
    { code: "kh", name: "កម្ពុជា" },
    { code: "ki", name: "Kiribati" },
    { code: "km", name: "جزر القمر" },
    { code: "kn", name: "Saint Kitts and Nevis" },
    { code: "kp", name: "조선민주주의인민공화국" },
    { code: "kr", name: "대한민국" },
    { code: "kw", name: "الكويت" },
    { code: "ky", name: "Cayman Islands" },
    { code: "kz", name: "Қазақстан" },
    { code: "la", name: "ລາວ" },
    { code: "lb", name: "لبنان" },
    { code: "lc", name: "Saint Lucia" },
    { code: "li", name: "Liechtenstein" },
    { code: "lk", name: "ශ්‍රී ලංකාව" },
    { code: "lr", name: "Liberia" },
    { code: "ls", name: "Lesotho" },
    { code: "lt", name: "Lietuva" },
    { code: "lu", name: "Lëtzebuerg" },
    { code: "lv", name: "Latvija" },
    { code: "ly", name: "ليبيا" },
    { code: "ma", name: "المغرب" },
    { code: "mc", name: "Monaco" },
    { code: "md", name: "Moldova" },
    { code: "me", name: "Crna Gora" },
    { code: "mf", name: "Saint-Martin" },
    { code: "mg", name: "Madagasikara" },
    { code: "mh", name: "Marshall Islands" },
    { code: "mk", name: "Северна Македонија" },
    { code: "ml", name: "Mali" },
    { code: "mm", name: "မြန်မာ" },
    { code: "mn", name: "Монгол улс" },
    { code: "mo", name: "澳門" },
    { code: "mp", name: "Northern Mariana Islands" },
    { code: "mq", name: "Martinique" },
    { code: "mr", name: "موريتانيا" },
    { code: "ms", name: "Montserrat" },
    { code: "mt", name: "Malta" },
    { code: "mu", name: "Maurice" },
    { code: "mv", name: "ދިވެހިރާއްޖެ" },
    { code: "mw", name: "Malawi" },
    { code: "mx", name: "México" },
    { code: "my", name: "Malaysia" },
    { code: "mz", name: "Moçambique" },
    { code: "na", name: "Namibia" },
    { code: "nc", name: "Nouvelle-Calédonie" },
    { code: "ne", name: "Niger" },
    { code: "nf", name: "Norfolk Island" },
    { code: "ng", name: "Nigeria" },
    { code: "ni", name: "Nicaragua" },
    { code: "nl", name: "Nederland" },
    { code: "no", name: "Norge" },
    { code: "np", name: "नेपाल" },
    { code: "nr", name: "Nauru" },
    { code: "nu", name: "Niue" },
    { code: "nz", name: "New Zealand" },
    { code: "om", name: "عُمان" },
    { code: "pa", name: "Panamá" },
    { code: "pe", name: "Perú" },
    { code: "pf", name: "Polynésie française" },
    { code: "pg", name: "Papua New Guinea" },
    { code: "ph", name: "Pilipinas" },
    { code: "pk", name: "پاکستان" },
    { code: "pl", name: "Polska" },
    { code: "pm", name: "Saint-Pierre-et-Miquelon" },
    { code: "pn", name: "Pitcairn Islands" },
    { code: "pr", name: "Puerto Rico" },
    { code: "ps", name: "فلسطين" },
    { code: "pt", name: "Portugal" },
    { code: "pw", name: "Palau" },
    { code: "py", name: "Paraguay" },
    { code: "qa", name: "قطر" },
    { code: "re", name: "La Réunion" },
    { code: "ro", name: "România" },
    { code: "rs", name: "Србија" },
    { code: "ru", name: "Россия" },
    { code: "rw", name: "Rwanda" },
    { code: "sa", name: "المملكة العربية السعودية" },
    { code: "sb", name: "Solomon Islands" },
    { code: "sc", name: "Seychelles" },
    { code: "sd", name: "السودان" },
    { code: "se", name: "Sverige" },
    { code: "sg", name: "Singapura" },
    { code: "sh", name: "Saint Helena" },
    { code: "si", name: "Slovenija" },
    { code: "sj", name: "Svalbard og Jan Mayen" },
    { code: "sk", name: "Slovensko" },
    { code: "sl", name: "Sierra Leone" },
    { code: "sm", name: "San Marino" },
    { code: "sn", name: "Sénégal" },
    { code: "so", name: "Soomaaliya" },
    { code: "sr", name: "Suriname" },
    { code: "ss", name: "South Sudan" },
    { code: "st", name: "São Tomé e Príncipe" },
    { code: "sv", name: "El Salvador" },
    { code: "sx", name: "Sint Maarten" },
    { code: "sy", name: "سوريا" },
    { code: "sz", name: "eSwatini" },
    { code: "tc", name: "Turks and Caicos Islands" },
    { code: "td", name: "Tchad" },
    { code: "tf", name: "Terres australes françaises" },
    { code: "tg", name: "Togo" },
    { code: "th", name: "ประเทศไทย" },
    { code: "tj", name: "Тоҷикистон" },
    { code: "tk", name: "Tokelau" },
    { code: "tl", name: "Timor-Leste" },
    { code: "tm", name: "Türkmenistan" },
    { code: "tn", name: "تونس" },
    { code: "to", name: "Tonga" },
    { code: "tr", name: "Türkiye" },
    { code: "tt", name: "Trinidad and Tobago" },
    { code: "tv", name: "Tuvalu" },
    { code: "tw", name: "臺灣" },
    { code: "tz", name: "Tanzania" },
    { code: "ua", name: "Україна" },
    { code: "ug", name: "Uganda" },
    { code: "um", name: "U.S. Minor Outlying Islands" },
    { code: "us", name: "United States" },
    { code: "uy", name: "Uruguay" },
    { code: "uz", name: "Oʻzbekiston" },
    { code: "va", name: "Città del Vaticano" },
    { code: "vc", name: "Saint Vincent and the Grenadines" },
    { code: "ve", name: "Venezuela" },
    { code: "vg", name: "British Virgin Islands" },
    { code: "vi", name: "U.S. Virgin Islands" },
    { code: "vn", name: "Việt Nam" },
    { code: "vu", name: "Vanuatu" },
    { code: "wf", name: "Wallis-et-Futuna" },
    { code: "ws", name: "Samoa" },
    { code: "xk", name: "Kosovë" },
    { code: "ye", name: "اليمن" },
    { code: "yt", name: "Mayotte" },
    { code: "za", name: "South Africa" },
    { code: "zm", name: "Zambia" },
    { code: "zw", name: "Zimbabwe" },
];
