/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MenuRouteImport } from './routes/_menu'
import { Route as MenuCardsRouteImport } from './routes/_menu/_cards'
import { Route as MenuAuthRouteImport } from './routes/_menu/_auth'
import { Route as MenuCardsIndexRouteImport } from './routes/_menu/_cards/index'
import { Route as MenuAuthProfileRouteImport } from './routes/_menu/_auth/profile'
import { Route as MenuCardsCardsIdRouteImport } from './routes/_menu/_cards/cards.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCardsRoute = MenuCardsRouteImport.update({
  id: '/_cards',
  getParentRoute: () => MenuRoute,
} as any)
const MenuAuthRoute = MenuAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MenuRoute,
} as any)
const MenuCardsIndexRoute = MenuCardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuCardsRoute,
} as any)
const MenuAuthProfileRoute = MenuAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuCardsCardsIdRoute = MenuCardsCardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => MenuCardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MenuCardsIndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof MenuAuthProfileRoute
  '/cards/$id': typeof MenuCardsCardsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MenuCardsIndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof MenuAuthProfileRoute
  '/cards/$id': typeof MenuCardsCardsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_menu': typeof MenuRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_menu/_auth': typeof MenuAuthRouteWithChildren
  '/_menu/_cards': typeof MenuCardsRouteWithChildren
  '/_menu/_auth/profile': typeof MenuAuthProfileRoute
  '/_menu/_cards/': typeof MenuCardsIndexRoute
  '/_menu/_cards/cards/$id': typeof MenuCardsCardsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/ocr'
    | '/reset-password'
    | '/profile'
    | '/cards/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/ocr'
    | '/reset-password'
    | '/profile'
    | '/cards/$id'
  id:
    | '__root__'
    | '/_menu'
    | '/library'
    | '/login'
    | '/ocr'
    | '/reset-password'
    | '/_menu/_auth'
    | '/_menu/_cards'
    | '/_menu/_auth/profile'
    | '/_menu/_cards/'
    | '/_menu/_cards/cards/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MenuRoute: typeof MenuRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OcrRoute: typeof OcrRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu/_cards': {
      id: '/_menu/_cards'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuCardsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/_auth': {
      id: '/_menu/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuAuthRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/_cards/': {
      id: '/_menu/_cards/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuCardsIndexRouteImport
      parentRoute: typeof MenuCardsRoute
    }
    '/_menu/_auth/profile': {
      id: '/_menu/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MenuAuthProfileRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/_cards/cards/$id': {
      id: '/_menu/_cards/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof MenuCardsCardsIdRouteImport
      parentRoute: typeof MenuCardsRoute
    }
  }
}

interface MenuAuthRouteChildren {
  MenuAuthProfileRoute: typeof MenuAuthProfileRoute
}

const MenuAuthRouteChildren: MenuAuthRouteChildren = {
  MenuAuthProfileRoute: MenuAuthProfileRoute,
}

const MenuAuthRouteWithChildren = MenuAuthRoute._addFileChildren(
  MenuAuthRouteChildren,
)

interface MenuCardsRouteChildren {
  MenuCardsIndexRoute: typeof MenuCardsIndexRoute
  MenuCardsCardsIdRoute: typeof MenuCardsCardsIdRoute
}

const MenuCardsRouteChildren: MenuCardsRouteChildren = {
  MenuCardsIndexRoute: MenuCardsIndexRoute,
  MenuCardsCardsIdRoute: MenuCardsCardsIdRoute,
}

const MenuCardsRouteWithChildren = MenuCardsRoute._addFileChildren(
  MenuCardsRouteChildren,
)

interface MenuRouteChildren {
  MenuAuthRoute: typeof MenuAuthRouteWithChildren
  MenuCardsRoute: typeof MenuCardsRouteWithChildren
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuAuthRoute: MenuAuthRouteWithChildren,
  MenuCardsRoute: MenuCardsRouteWithChildren,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MenuRoute: MenuRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OcrRoute: OcrRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
